{% set version = "0.1.3" %}

package:
  name: egal
  version: {{ version }}

source:
  url: https://github.com/uclmr/egal/archive/{{ version }}.tar.gz
  sha256: 78ff21f7a1f5eabb67377ddbdd3f3a8c73cc9c6a16f6f37f5c896540c2967e84

build:
  number: 1004
  skip: True  # [py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jupyter

test:
  imports:
    - egal

about:
  home: https://github.com/uclmr/egal
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Easy SVG drawing in jupyter and elsewhere'

extra:
  recipe-maintainers:
    - ocefpaf
