appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jAK/Wx1F1jbEPJXo48J7pN2TACyODPyET0XaaXRaoUdBJlyrcbExJBOLvyd7pL0tGyUs0zPdMWICptldO6jeFz/o9KhVYYOYMunzTz9dm7RD0F84ZgffQvxKjwJB9MzPQivIvUoyelkJUA2Bk3+rS4skS+S6pSHBZk+tmynrJiTZA1DZDTZwNqNuvvm+GUnYNgMqgAtasArQ1/7xQsxT4/DYBACMe6oPf5X0+XRuR0sBMrlod+QIb0TiRV8ucFNa1WZJFgGTy9wI0ae8N9MmLo5q1/MgfAIcx7iudgMNiZ1BxpiwbjJjkNREVHSjYArK0eap0u7lIsfD54wBKHi7rII8EFuvQ2yVtD6s0pOIpm1vIedc22oYh7pyOPSiShb0pf/LDlDnKvkt7DL2+RLGgDRV8JzW8xnLRAHp4G5dXAJfTpxolzX5pt47iWxJYPiGGO8sjyHpBuZ/yUM8a488rUCjRsTwKutqJvIEYPXAki0sEy6ko2AM+p5E6IhOE6LR7e4F1vjK+xQwriwPIeXU9UGdDSJqfrGBpJzeqaZRDsKiU/Halh4JeTona9boKzOZ+vSvFkCEdZIv5wfgs2Xa5g4KpI9VHDWApFBMmO79zfGnQHj5AJUR5mqeRpmb0fUVlI44SZQqbTC2obUmyQc3hrsTH/tIBoZ8GObSzo+7+WE=}
conda_forge_output_validation: true
