travis:
  secure:
    BINSTAR_TOKEN: g/pLSWodQTini4jO7XVQ8tBuZHAS3DShfislMK1eKB/qm5MdQDJbWWuINnnZBc/mHu/EkEdmRduNLCFR6LQkZ8yN7xrhIoEhM3eT0GySvhMC+AxcFFvAIpT3VgvSUTWS/b0ifL7YstUM7n7ug0EKm+jH5A6uKzrF0QJrzp/TFM2e2cu55Br8H4/mGck4tqBc9VuqhbA1qKpSgqkoJIj31jJVwhhAJiI/ocRoU/7PpICw+5vGRuvsTMf5i2HZ70/7ASNiy5Fp9FhR7TPfoA6+TDwPfp4FzAwATbcJ4lNy/Uli56pUVU/ZzaRviPFlH6qkTxhwzHbByYeDX+4+AhJiSFizV3H7RTWRuuULUm93RspP3F1rmpBUSbN48tOPBqgwMVM1DOs6QUc+D0CcKIeTzf4X9K81/i9Q98NhzHv8DecuWxS8QdZxUL7i3DBYgFs5LCCCJaC13z0fgTTu52QCYR0kF8t2FyKw4UhNTqt48nZLuh0s+0bFtkAV4he6ubZVW9XReELZm9/TBzjk5A0wkVFaZbtGFZgvX1zRn6tTNsyvtwCH5fTM459Sqqs6jpqApfzx2/T9rkuTdyDTeIzCUxaCvhTswvOTFalxDxR+8jzzrJ4lmQzeZLFjLllEzy9c4x2VQytGJBNHEaVeJc2ed5PNbBo0eSYGvUdr2tnxVXg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
